### ISSUE TITLE
Favicon icon / Akash logo is distorted 

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website#385]
The Akash logo (favicon) appears compressed and distorted.

Examples from google chrome:
<img width="246" alt="Screenshot 2024-10-08 at 21 45 30" src="https://github.com/user-attachments/assets/c531f931-7152-456d-a168-54d04ea24fd7">
<img width="475" alt="Screenshot 2024-10-08 at 21 48 01" src="https://github.com/user-attachments/assets/39771416-79ea-4ed2-aa17-d4c4e6f7d6b1">

**Comment by Epic-SX** [comment]
Hello @aktdenis 
I can fix this issue.

**Comment by piber-dev** [comment]
facicon found [here](https://raw.githubusercontent.com/akash-network/website/refs/heads/main/public/favicon.ico) is 30x26, should likely be 32x32 though different sizes are supported. should at least be square. the issue is likely because the akash-sign-red.svg file is not square and the person who made the favicon didn't check too thoroughly. i made a .ico file by expanding the canvas size of this file and then reduced the image size to 32x32, will make a PR in a sec.

**Comment by piber-dev** [comment]
@aktdenis is this issue resolved after my PR or are there more instances of this distorted favicon?

**Comment by aktdenis** [comment]
@HoomanDgtl please close this issue

**Comment by HoomanDgtl** [comment]
this is done in #386
