### ISSUE TITLE
Development page content should be moved to Community

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website#5]
The content in the development section should really be apart of the community section, so new and existing users can learn about sigs, wgs, Akash Insiders and other community based programming. 

The Development section should focus on technical contributions including ways for technical users to contribute to areas like:
- Support repo
- Awesome Akash
- technical bounties
- technical documentation
- Cloudmos open source tools
- technical product and engineering roadmap
- discussions for further technical conversations

**Comment by aktdenis** [comment]
I'm having a look at this issue. 

Quick question: 
Which items from `Development` page should be in the `Community` page? I know community is involved, but it seems all items are development related. 

I did some quick research and for example, Ethereum, Solana, Polkadot etc. all have separated sections for "Community" (dedicated for events, community news, content,... ) and "Development" (for all engineering things - even if the community is involved). It kinda looks like an established ux pattern in web3 world.

I'll explore how to bring some of the items you've stated above to `Development` page and we might have to redesign some of the existing items there.

**Comment by aktdenis** [comment]
Considering the points mentioned above, we could add them to the "Development" page. 
Here's my suggested structure with these items included.

Before viewing design drafts please consider the proposal to restructure the menu [here](https://github.com/akash-network/website/issues/287).

"Development" dropdown menu:
<img width="213" alt="Screenshot 2024-06-27 at 10 55 47" src="https://github.com/akash-network/website/assets/116030971/1a7c53e8-bd15-4906-b53c-a833267a7f37">

Secondary horizontal nav on the "Development" page
<img width="900" alt="Screenshot 2024-06-27 at 10 56 46" src="https://github.com/akash-network/website/assets/116030971/8124790f-cb8a-48fb-b810-5bbcf91387d6">

Design draft with items mentioned by @brewsterdrinkwater (*copy updates are not part of this draft)
![akash-development](https://github.com/akash-network/website/assets/116030971/9ac52bac-441b-4f2c-b7b6-4237f7bfaa99)
Couple of explanation points for the draft above:
- Community calendar is a sticky floater - which stays in the bottom right corner. When clicked, it opens a pop-up with a view of a calendar. With this approach we actively invite visitors to join meetings while they browse through "Development" pages. The look and feel of the calendar should resonate with [this example from tailwind](https://tailwindui.com/components/application-ui/data-display/calendars#component-2c77a3f6925b437e983e0d07fe3288b1). 
- Important to note the section for "Product Strategy" is not included in any sections above. First we have to re-think the [existing page](https://akash.network/development/product-strategy/) and define what information is relevant, needs to be removed or changed. But we do have a CTA or a button for Product roadmap (on github) communicated in the main and secondary nav.
- 

the whole page has a different experience, so we have to think what happens to other sub-pages. Below an example of community groups:
![akash-community-groups-sigs](https://github.com/akash-network/website/assets/116030971/578370a2-ee2b-4eeb-9011-0790f433ff9e)

This issue is not finalized, further discussion and feedback is welcomed and appreciated.

**Comment by ShinySyntax** [comment]
Hello, @aktdenis 
Is this issue resolved?
I can do it.

**Comment by aktdenis** [comment]
hello @kindlyman343423 , not yet. 
we still need to discuss further development and direction. 

if you're interested in joining working group for akash website please join our next meeting on Thu, Aug 22nd. 

here is the calendar of all meetings;
https://akash.network/development/welcome/

**Comment by aktdenis** [comment]
@brewsterdrinkwater any thoughts on the drafts above?

**Comment by ShinySyntax** [comment]
Got it. @aktdenis 
Thanks for your contact.

**Comment by aktdenis** [comment]
adding a mockup for "community calendar" sticky button. <img width="2244" alt="Screenshot 2024-08-19 at 19 17 05" src="https://github.com/user-attachments/assets/d0f2a3e5-75a8-4da9-bd2d-8a3929391d8f">

**Comment by brewsterdrinkwater** [comment]
I love this. 

I just want to add the calendar button to as many pages as possible. It will also be great to add [bounties page](https://github.com/orgs/akash-network/projects/6/views/2?sliceBy%5Bvalue%5D=%24%24+Bounty+%24%24).

**Comment by aktdenis** [comment]
@HoomanDgtl Let's close this issue. I'll prepare a new one with new info and direction.

**Comment by HoomanDgtl** [comment]
this is resolved
